apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "ssh-monitor"
spec:
  kprobes:
  - call: "tcp_v4_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DPort"
        values:
        - "22"
      matchActions:
      - action: Post
