apiVersion: 1

datasources:
  # ── VictoriaMetrics (Prometheus compatible) ──────────────────
  - name: VictoriaMetrics
    uid: P4169E866C3094E38
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    editable: true

  # ── Loki (primary for dashboards) ─────────────────────────
  - name: VictoriaLogs-Loki
    uid: P8855254D92C56053
    type: loki
    access: proxy
    url: http://victorialogs:9428
    isDefault: true
    jsonData:
      maxLines: 1000
    editable: true
