#!/usr/bin/env python3
"""
DTIClaw DOCX Writer Script
Generate professional .docx from structured markdown input.
Usage: python3 docx_writer.py --title "..." --author "..." --input research.md --output report.docx
"""

import argparse
import sys
import os
from datetime import datetime
from pathlib import Path

try:
    from docx import Document
    from docx.shared import Pt, Inches, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
except ImportError:
    print("ERROR: python-docx not installed. Run: pip install python-docx")
    sys.exit(1)


def create_document(title, author, content_file, output_file):
    doc = Document()
    
    # Page setup
    section = doc.sections[0]
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(3)
    section.right_margin = Cm(3)
    
    # Default font
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)
    style.paragraph_format.space_after = Pt(6)
    
    # === COVER PAGE ===
    for _ in range(6):
        doc.add_paragraph()
    
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(title)
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
    
    doc.add_paragraph()
    
    meta_lines = [
        f"Author: {author}",
        f"Date: {datetime.now().strftime('%d %B %Y')}",
        "Generated by DTIClaw 🦞"
    ]
    for line in meta_lines:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(line)
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    
    doc.add_page_break()
    
    # === TABLE OF CONTENTS (placeholder) ===
    toc_heading = doc.add_heading('Table of Contents', level=1)
    doc.add_paragraph('[Auto-generated TOC — update in Word: References → Update Table]')
    doc.add_page_break()
    
    # === CONTENT ===
    if content_file and os.path.exists(content_file):
        with open(content_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        lines = content.split('\n')
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            
            # Headings
            if line.startswith('# ') and not line.startswith('## '):
                text = line[2:].strip()
                doc.add_heading(text, level=1)
                i += 1
                continue
            elif line.startswith('## ') and not line.startswith('### '):
                text = line[3:].strip()
                doc.add_heading(text, level=2)
                i += 1
                continue
            elif line.startswith('### '):
                text = line[4:].strip()
                doc.add_heading(text, level=3)
                i += 1
                continue
            
            # Markdown table: baris '|...|' diikuti baris pemisah '|---|' -> tabel Word asli
            if line.startswith('|') and i + 1 < len(lines) and \
               set(lines[i + 1].strip()) <= set('|-: ') and '|' in lines[i + 1]:
                rows = []
                while i < len(lines) and lines[i].strip().startswith('|'):
                    raw = lines[i].strip()
                    i += 1
                    if set(raw) <= set('|-: '):  # baris pemisah header
                        continue
                    cells = [c.strip().replace('**', '') for c in raw.strip('|').split('|')]
                    rows.append(cells)
                if rows:
                    ncol = max(len(r) for r in rows)
                    table = doc.add_table(rows=0, cols=ncol)
                    table.style = 'Table Grid'
                    for ridx, cells in enumerate(rows):
                        cells = cells + [''] * (ncol - len(cells))
                        wcells = table.add_row().cells
                        for wc, val in zip(wcells, cells):
                            wc.text = val
                            if ridx == 0:
                                for para in wc.paragraphs:
                                    for r in para.runs:
                                        r.bold = True
                continue

            # Bullet points
            if line.startswith('- ') or line.startswith('* '):
                text = line[2:].strip()
                p = doc.add_paragraph(text, style='List Bullet')
                i += 1
                continue
            
            # Numbered lists
            if line and line[0].isdigit() and '. ' in line[:5]:
                idx = line.index('. ') + 2
                text = line[idx:].strip()
                p = doc.add_paragraph(text, style='List Number')
                i += 1
                continue
            
            # Empty lines = paragraph break
            if not line:
                i += 1
                continue
            
            # Regular paragraph
            p = doc.add_paragraph(line)
            
            # Bold markers: **text**
            if '**' in line:
                # Rebuild paragraph with bold sections
                p.clear()
                parts = line.split('**')
                for j, part in enumerate(parts):
                    if j % 2 == 1:  # odd = bold
                        run = p.add_run(part)
                        run.bold = True
                    else:
                        p.add_run(part)
            
            i += 1
    
    # === FOOTER with page numbers ===
    footer = section.footer
    footer.is_linked_to_previous = False
    p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run('Page ')
    run.font.size = Pt(9)
    
    # Add page number field
    fldChar1 = p._p.makeelement(qn('w:r'), {})
    p._p.append(fldChar1)
    
    os.makedirs(os.path.dirname(os.path.abspath(output_file)), exist_ok=True)
    doc.save(output_file)
    print(f"✅ Document saved: {output_file}")
    return output_file


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='DTIClaw DOCX Writer')
    parser.add_argument('--title', required=True, help='Document title')
    parser.add_argument('--author', default='Atok Tajuddin', help='Author name')
    parser.add_argument('--input', help='Markdown content file')
    parser.add_argument('--output', required=True, help='Output .docx path')
    
    args = parser.parse_args()
    
    if args.input and not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}")
        sys.exit(1)
    
    create_document(args.title, args.author, args.input, args.output)
